apiVersion: v1                                                                                                            
                                                                                 
data:                                                                                                                     
                                                                                 
  application-config.json:                                                                                                
                                                                             
   '{
        "server.port":"8088",
        "application.url": "http://cloudconsole.orelit.com/ResetPassword?code=",
        "keycloak.realm": "Cloud7-Realm",
        "keycloak.ssl-required": "external",
        "keycloak.resource": "ivolve.cloud7",
        "keycloak.use-resource-role-mappings": "true",
        "keycloak.bearer-only": "true",
        "keycloak_clientId": "admin-cli",
        "keycloak_master_relem": "master",
        "keycloak_url_access_token": "http://keycloak:8080/auth/realms/Cloud7-Realm/protocol/openid-connect/token",
        "keycloak.auth-server-url": "http://keycloak:8080/auth",
        "spring.redis.host": "redis",
        "spring.redis.port": "6379",

        "payment_url": "http://payment:8084/api/v1/",
        "node_url": "http://ansible-service:3005/api/ansible" ,
        "ansible_url": "http://ansible-service:3005/api/ansible",
        
        "org.jobrunr.background-job-server.enabled": "true",
        "org.jobrunr.dashboard.enabled": "true",

        "contract_service_url": "http://contract-backend:8082/api/v1/",
        "helpdesk_service_url": "http://helpdesk:8091/api/v1/",

        "spring.datasource.url": "jdbc:mysql://10.2.0.4:3306/cloud7?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false",
        "spring.datasource.driver-class-name": "com.mysql.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL5Dialect",

        "spring.jpa.hibernate.ddl-auto": "update",

        "upload_file_path": "/home/ubuntu/documents/uploads/",
        "marketplace_file_path" : "/home/ubuntu/documents/marketplace/",


        "spring.servlet.multipart.max-file-size": "10MB",
        "spring.servlet.multipart.max-request-size": "10MB",

        "spring.jpa.properties.hibernate.jdbc.time_zone": "UTC",

        "spring.cloud.vault.uri": "http://vault.c7vault.svc.cluster.local:8200",
        "spring.cloud.vault.token": "hvs.wGdBFws44FV3lWGCZGexQi7p",
	"spring.cloud.vault.generic.enabled" : "true",
        "spring.cloud.vault.generic.backend" : "c7",
        "spring.cloud.vault.generic.default-context" : "backend",
        "spring.jpa.show-sql" : "false",
        "spring.boot.admin.client.url" : "http://cloud7-admin:8071",
        "spring.mail.host" : "smtp.gmail.com",
        "spring.mail.port" : "587",
        "spring.mail.username" : "testemaildcm34@gmail.com",
        "spring.mail.password" : "dcmtestemail",
        "spring.mail.properties.mail.smtp.starttls.enable" : "true",
        "spring.mail.properties.mail.smtp.starttls.required" : "true",
        "spring.mail.properties.mail.smtp.auth" : "true",
        "spring.mail.properties.mail.smtp.connectiontimeout" : "5000",
        "spring.mail.properties.mail.smtp.timeout" : "5000",
        "spring.mail.properties.mail.smtp.writetimeout" : "5000",

        "spring.datasource.hikari.minimumIdle" : "20",
        "spring.datasource.hikari.maximumPoolSize" : "200",
        "spring.datasource.hikari.idleTimeout" : "120000",
        "spring.datasource.hikari.maxLifetime" : "1800000",
        "spring.datasource.hikari.leakDetectionThreshold" : "180000",
        "spring.datasource.hikari.leak-detection-threshold" : "480000",
        "spring.datasource.hikari.validationTimeout" : "300000",

        "resilience4j.timelimiter.metrics.enabled" : "true",
        "resilience4j.ratelimiter.instances.default.limitForPeriod" : "5",
        "resilience4j.ratelimiter.instances.default.limitRefreshPeriod" : "1m",
        "resilience4j.ratelimiter.instances.other.limitForPeriod" : "2",
        "resilience4j.ratelimiter.instances.other.limitRefreshPeriod" : "10s",
        "resilience4j.ratelimiter.instances.otp.limitForPeriod" : "1",
        "resilience4j.ratelimiter.instances.otp.limitRefreshPeriod" : "30s",
        
        "resilience4j.bulkhead.instances.default.maxConcurrentCalls" : "10",
        "resilience4j.bulkhead.instances.sample-api.maxConcurrentCalls" : "10",
        "spring.flyway.schemas" : "cloud7",
        "spring.cache.redis.time-to-live" : "100s",
        "spring.cache.redis.type" : "simple",
        "server_api_url" : "http://localhost:8088/",
        "server_api_version" : "api/v1/",
        "domain_url" : "http://localhost:8088/api/v1/",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb",
        "spring.flyway.baselineOnMigrate" : "true",
        "spring.flyway.check-location" : "true",
        "spring.flyway.validateOnMigrate" : "false",
        "spring.flyway.locations" : "classpath:db/migration",
        "spring.flyway.enabled" : "true",
        "logging.level.root" : "WARN",
        "logging.level.com.ivolve" : "TRACE",

        "spring.redis.jedis.pool.max-active" : "200",
        "spring.redis.jedis.pool.max-idle" : "128",
        "spring.redis.jedis.pool.min-idle" : "16",
        "spring.redis.password" : "Ec<vUBxPBw#}9NX",
        "spring.datasource.hikari.minimum-idle" : "20",
        "spring.datasource.hikari.max-lifetime" : "1800000",
        "spring.datasource.hikari.connection-timeout" : "60000",
        "spring.datasource.hikari.maximum-pool-size" : "200",
        "spring.datasource.hikari.idle-timeout" : "120000",
        "spring.datasource.hikari.metrics.enabled" : "true",
        "spring.data.mongodb.host" : "10.2.0.4",
        "spring.data.mongodb.port" : "27017",
	"spring.data.mongodb.authentication-database" : "admin",
	"spring.data.mongodb.database" : "DCM",
	"logging.level.org.springframework.data.mongodb.core.MongoTemplate" : "DEBUG",
        "encrypt_key" : "&m7y#JfwVHkPEjymyjwwa$#bjyxL86GkDg7DQUbM",
	"keycloak.credentials.secret" : "TPxUoTIlsOPAn5hwJup4s68m5a8hqUDZ",
  	"keycloak_admin_password": "letmein@123",
 	 "keycloak_admin_username": "admin",
 	 "spring.data.mongodb.password": "letmein@123",
 	 "spring.data.mongodb.username": "c7",
  	"spring.datasource.password": "letmein@123",
  	"spring.datasource.username": "c7"
        
        
        
        
        
        
   }'     
kind: ConfigMap
metadata:
  name: application-config-backend
  namespace: c7
