---
apiVersion: v1
data:
  application-config.json:
    '{ 
       "server.port": "8082", "application.url":
       "http://cloudconsole.orelit.com", "spring.datasource.url":
       "jdbc:mysql://10.2.0.4:3306/cloud7?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false",
       "spring.datasource.username" : "c7", 
       "spring.datasource.driver-class-name":"com.mysql.jdbc.Driver", 
       "spring.jpa.hibernate.ddl-auto": "update",
       "spring.jpa.show-sql": "false", 
       "spring.cloud.vault.uri":"http://vault.c7vault.svc.cluster.local:8200", 
       "spring.cloud.vault.token":"hvs.wGdBFws44FV3lWGCZGexQi7p",
       "spring.cloud.vault.generic.default-context":"backend",
       "spring.boot.admin.client.url" : "http://cloud7-admin:8071",
       "org.jobrunr.background-job-server.enabled": "true",
       "org.jobrunr.dashboard.enabled": "true",

        "spring.datasource.hikari.minimumIdle" : "20",
        "spring.datasource.hikari.maximumPoolSize" : "200",
        "spring.datasource.hikari.idleTimeout" : "120000",
        "spring.datasource.hikari.maxLifetime" : "1800000",
        "spring.datasource.hikari.leakDetectionThreshold" : "180000",
        "spring.datasource.hikari.leak-detection-threshold" : "480000",
        "spring.datasource.hikari.validationTimeout" : "300000",

        "resilience4j.timelimiter.metrics.enabled" : "true",
        "resilience4j.ratelimiter.instances.default.limitForPeriod" : "5",
        "resilience4j.ratelimiter.instances.default.limitRefreshPeriod" : "1m",
        "resilience4j.ratelimiter.instances.other.limitForPeriod" : "2",
        "resilience4j.ratelimiter.instances.other.limitRefreshPeriod" : "10s",
        "resilience4j.ratelimiter.instances.otp.limitForPeriod" : "1",
        "resilience4j.ratelimiter.instances.otp.limitRefreshPeriod" : "30s",
        
        "resilience4j.bulkhead.instances.default.maxConcurrentCalls" : "10",
        "resilience4j.bulkhead.instances.sample-api.maxConcurrentCalls" : "10",
          "keycloak.credentials.secret": "TPxUoTIlsOPAn5hwJup4s68m5a8hqUDZ",
        "keycloak_admin_password": "letmein@123",
        "keycloak_admin_username": "admin",
        "spring.data.mongodb.password": "letmein@123",
        "spring.data.mongodb.username": "noc",
        "spring.datasource.password": "letmein@123",
        "encrypt_key" : "&m7y#JfwVHkPEjymyjwwa$#bjyxL86GkDg7DQUbM",
        "spring.datasource.username": "c7"
     }'
kind: ConfigMap
metadata:
  name: application-config-contract
  namespace: c7
