apiVersion: v1                                                                                                            
                                                                                 
data:                                                                                                                     
                                                                                 
  application-config.json:                                                                                                
                                                                             
   '{
        
        "server.port": "8091",
        "application.url": "http://cloudconsole.orelit.com", 
	"spring.cloud.vault.uri": "http://vault.c7vault.svc.cluster.local:8200",
	"spring.cloud.vault.token": "hvs.wGdBFws44FV3lWGCZGexQi7p",
	"spring.cloud.vault.generic.backend": "c7",
	"spring.cloud.vault.generic.default-context": "backend",
 
        "spring.datasource.url": "jdbc:mysql://10.2.0.4:3306/cloud7?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false",
        "spring.datasource.driver-class-name": "com.mysql.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers" : "true",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb",
        "spring.jpa.properties.hibernate.jdbc.time_zone": "UTC",
        "security.basic.enabled" : "false",
        "spring.datasource.hikari.minimumIdle" : "20",
        "spring.datasource.hikari.maximumPoolSize" : "200",
        "spring.datasource.hikari.idleTimeout" : "120000",
        "spring.datasource.hikari.maxLifetime" : "1800000",
        "spring.datasource.hikari.leakDetectionThreshold" : "180000",
        "spring.datasource.hikari.pool-name" : "my-pool",
        "spring.datasource.hikari.initialization-fail-fast" :"true",
        "spring.datasource.hikari.leak-detection-threshold" : "480000",
        "spring.datasource.hikari.connection-test-query" : "SELECT 1",
        
        "spring.datasource.hikari.validationTimeout" : "300000",
        "spring.datasource.hikari.minimum-idle" : "20",
        "spring.datasource.hikari.max-lifetime" : "1800000",
        "spring.datasource.hikari.connection-timeout" : "60000",
        "spring.datasource.hikari.maximum-pool-size" : "200",
        "spring.datasource.hikari.idle-timeout" : "120000",
        "spring.datasource.hikari.metrics.enabled" : "true",

        "spring.servlet.multipart.max-file-size": "10MB",
        "spring.servlet.multipart.max-request-size": "10MB",

        "zipkin.Url" : "http://localhost:9411/",
        "logging.level.root" : "WARN",
        "logging.level.com.ivolve" : "TRACE",

        "logging.file.name" : "logs/platform-logger.log",
        "spring.boot.admin.client.url" : "http://localhost:8071",
        "management.endpoints.web.exposure.include" : "*",
        "management.endpoint.health.show-details" : "always",
	  "keycloak.credentials.secret": "TPxUoTIlsOPAn5hwJup4s68m5a8hqUDZ",
	  "keycloak_admin_password": "letmein@123",
 	 "keycloak_admin_username": "admin",
 	 "spring.data.mongodb.password": "letmein@123",
 	 "spring.data.mongodb.username": "noc",
 	 "spring.datasource.password": "letmein@123",
  	"spring.datasource.username": "c7"
   }'     
kind: ConfigMap
metadata:
  name: application-config-helpdesk
  namespace: c7
