---
apiVersion: v1
data:
  application-config.json: '{ "server.port": "8084", "application.url":
    "http://cloudconsole.orelit.com", "spring.datasource.url":
    "jdbc:mysql://10.2.0.4:3306/cloud7?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false",
    "spring.datasource.driver-class-name": "com.mysql.jdbc.Driver",
    "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5Dialect",
    "spring.jpa.hibernate.ddl-auto": "update", "spring.jpa.show-sql": "false",
    "spring.jpa.properties.hibernate.jdbc.time_zone" : "UTC", "payment_url":
    "http://payment:8084/api/v1/", "logging.level.root": "WARN",
    "logging.level.com.cloud7" : "TRACE", "spring.cloud.vault.uri":
    "http://vault.c7vault.svc.cluster.local:8200",
    "spring.cloud.vault.token":"hvs.wGdBFws44FV3lWGCZGexQi7p",
      "keycloak.credentials.secret": "TPxUoTIlsOPAn5hwJup4s68m5a8hqUDZ",
  "keycloak_admin_password": "letmein@123",
  "keycloak_admin_username": "admin",
  "spring.data.mongodb.password": "letmein@123",
  "spring.data.mongodb.username": "noc",
  "spring.datasource.password": "letmein@123",
  "spring.datasource.username": "c7"
    }'
kind: ConfigMap
metadata:
  name: application-config-payment
  namespace: c7
